name: node_js_blog_practica

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  Cypress_job:
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar servidor
        run: npm start & 

      - name: Ejecutar Cypress 
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
        continue-on-error: true

      - name: Guardar resultado de Cypress
        run: echo "success" > result.txt
        if: success()
        continue-on-error: true

      - name: Guardar artefacto de Cypress
        uses: actions/upload-artifact@v4
        with:
          name: cypress-result
          path: result.txt

  
  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: cypress-result

      - name: Generar resultado de Cypress
        id: result
        run: echo "result=$(cat result.txt)" >> $GITHUB_ENV

      - name: Modificar README con badge
        uses: ./my-custom-action
        with:
          result: ${{ env.result }}
      
      - name: Publicar cambios en README.md
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || (git add README.md && git commit -m "Actualizar badge en README.md según resultados de tests")
          git push
        

  Deploy_job:
    runs-on: ubuntu-latest
    needs: Cypress_job  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20 
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Token de acceso a Vercel
          vercel-args: "--prod" # Despliegue en producción
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # ID de la organización
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # ID del proyecto en Vercel
    
  Notification_job:
    runs-on: ubuntu-latest
    needs: [linter_job, Cypress_job, Add_badge_job, Deploy_job]
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com 
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Resultado del workflow"
          body: |
            Resultado de los jobs:
            - Linter_job: ${{ needs.linter_job.result }}
            - Cypress_job: ${{ needs.Cypress_job.result }}
            - Add_badge_job: ${{ needs.Add_badge_job.result }}
            - Deploy_job: ${{ needs.Deploy_job.result }}
          to: miguelgandiajorda@gmail.com
          from: mgandia1999@gmail.com
        

  github-metricas:
    runs-on: ubuntu-latest
    needs: [Add_badge_job] 
    permissions:
      contents: write
    steps:
      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Generar métricas
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: miganjo99 
          template: classic
          base: header, activity
          config_timezone: Europe/Madrid
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 20
          plugin_languages_recent_days: 14

      - name: Agregar metricas al README
        run: echo "![Metrics](./github-metrics.svg)" >> README.md

      - name: Sincronizar con el remoto
        run: git pull --rebase origin main

      - name: Actualizar metricas en el README.md
        run: |
          git add README.md
          git commit -m "Actualizar metricas del README.md" || echo "Sin cambios para commit"
          git push origin main


  
  