name: node_js_blog_practica

on:
  push:
    branches:
      - main

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  Cypress_job:
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Cypress
        uses: cypress-io/github-action@v5
        with:
          install: false
          runTests: true
        continue-on-error: true

      - name: Guardar resultado de Cypress
        run: echo "success" > result.txt
        if: success()
        continue-on-error: true

      - name: Guardar artefacto de Cypress
        uses: actions/upload-artifact@v4
        with:
          name: cypress-result
          path: result.txt

  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: cypress-result

      - name: Generar resultado de Cypress
        id: result
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"

      - name: Modificar README con badge
        uses: .action.yml
        with:
          result: ${{ steps.result.outputs.cypress_outcome }}    