name: node_js_blog_practica

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  Cypress_job:
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar servidor
        run: npm start & 

      - name: Ejecutar Cypress 
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
        continue-on-error: true

      - name: Guardar resultado de Cypress
        run: echo "success" > result.txt
        if: success()
        continue-on-error: true

      - name: Guardar artefacto de Cypress
        uses: actions/upload-artifact@v4
        with:
          name: cypress-result
          path: result.txt

  
  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: cypress-result

      - name: Generar resultado de Cypress
        id: result
        run: echo "result=$(cat result.txt)" >> $GITHUB_ENV

      - name: Modificar README con badge
        uses: ./my-custom-action
        with:
          result: ${{ env.result }}
      
      - name: Publicar cambios en README.md
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || (git add README.md && git commit -m "Actualizar badge en README.md según resultados de tests")
          git push
        

  Deploy_job:
    runs-on: ubuntu-latest
    needs: Cypress_job  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20 
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Token de acceso a Vercel
          vercel-args: "--prod" # Despliegue en producción
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # ID de la organización
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # ID del proyecto en Vercel
    
  Notification_job:
    runs-on: ubuntu-latest
    if: always() 
    steps:
      - name: Enviar notificación por correo
        uses: tj-actions/send-email@v1.11
        with:
          server_address: smtp.gmail.com 
          server_port: 587 
          username: ${{ secrets.SMTP_USERNAME }} 
          password: ${{ secrets.SMTP_PASSWORD }} 
          subject: "Resultado del Workflow"
          body: |
            Hola,
            
            Aquí tienes los resultados del workflow ejecutado:
            - Linter_job: ${{ needs.linter_job.result }}
            - Cypress_job: ${{ needs.Cypress_job.result }}
            - Add_badge_job: ${{ needs.Add_badge_job.result }}
            - Deploy_job: ${{ needs.Deploy_job.result }}
            
            Saludos,
            GitHub Actions
          to: ${{ secrets.EMAIL_TO }} 
          from: ${{ secrets.SMTP_USERNAME }} 

  